### ISSUE TITLE
question: problem merging layer: library not found..

### ISSUE THREAD

**Issue by cesarpachon** [nsriram/aws-lambda-layer-example#1]
hi @nsriram, thanks for this article! was very helpful as I detected I was not adding "package.json" to the zip. but even now, with the zip uploaded with the nodejs/node_modules/async and nodejs/node_modules/package.json within, I always got the error "cannot find module 'async'". the lambda function shows that it is using the layer (version 4), both in the cli console and in the web console.. 
The code that fails in the lambda function is: 
let async = require('async') 

aws lambda update-function-configuration --function-name MY_LAMBDA --layers arn:aws:lambda:us-west-2:MY_ID:layer:MY_LAYER:4
{
    "Layers": [
        {
            "CodeSize": 21482560,
            "Arn": "arn:aws:lambda:us-west-2:MY_ID:layer:MY_LAYER:4"
        }
    ],
    "FunctionName": "MY_LAMBDA",
    "LastModified": "2018-12-18T23:44:34.062+0000",
    "RevisionId": "f55a6ab7-7b0b-494a-840c-87fb8371a117",
    "MemorySize": 128,
    "Version": "$LATEST",
    "Role": "arn:aws:iam::MY_ID:role/service-role/MY_ROLE",
    "Timeout": 30,
    "Runtime": "nodejs4.3",
    "TracingConfig": {
        "Mode": "PassThrough"
    },
    "CodeSha256": "hajYdqb+...=",
    "Description": "",
    "VpcConfig": { ... lot of stuff here .. },
    "CodeSize": 429123,
    "FunctionArn": "arn:aws:lambda:MY_ZONE:MY_ID:function:MY_LAMBDA",
    "Handler": "MY_HANDLER"
}
.. wonder if you have any suggestion... thanks!

**Comment by nsriram** [comment]
Is your NodeJS runtime the problem ? I notice ` "Runtime": "nodejs4.3",`.
- I tried the async node_module (https://github.com/caolan/async) and I was able to create a layer and use it in a lambda _(simple code that just uses async module)_.

```
const async = require('async');
const y = [];
exports.handler = (event, context, callback) => {
  async.forEach([1, 2, 3], (x) => {
    y.push(x ** 2);
  });
 callback(null, { squares: y });
};
```

Steps used to create the lambda layer and lambda.

```
aws lambda publish-layer-version --layer-name "async-lambda-layer" \
  --description "NodeJS module of Async library" \
  --license-info "MIT" \
  --compatible-runtimes "nodejs8.10" \
  --zip-file "fileb:////tmp/async-lambda-layer.zip"

aws lambda create-function \
        --region <AWS_REGION> \
        --function-name squareLambda \
        --handler 'squareLambda.handler' \
        --runtime nodejs8.10 \
        --role "arn:aws:iam::<AWS_ACCOUNT_ID>:role/<AWS_IAM_ROLE>" \
        --zip-file 'fileb:///tmp/squareLambda.js.zip' \
        --profile <AWS_PROFILE>

aws lambda update-function-configuration \
  --function-name squareLambda \
  --layers arn:aws:lambda:<AWS_REGION>:<AWS_ACCOUNT_ID>:layer:async-lambda-layer:1

aws lambda invoke --function-name squareLambda --log-type Tail --payload '{}' outputfile.txt
```
