### ISSUE TITLE
How to use reusable shared code base as lambda layers ?

### ISSUE THREAD

**Issue by devansvd** [nsriram/aws-lambda-layer-example#2]
For node_modules sounds good & works as expected when placing something inside  `nodejs/node_modules`, `nodejs/node8/node_modules (NODE_PATH)`. My question would be if i have a reusable shared code bases across lambda functions where do i place it & how can I use it ?

**Comment by nsriram** [comment]
Your reusable code can be made NPM module/library (if they are nodejs based) and published to an NPM repository (public/private). 
You can 'also' create lambda layer (artifact) from those node libraries and share across AWS Accounts using permissions.

**Comment by devansvd** [comment]
As node module will work since it is in `NODE_PATH`. But creating reusable codes as npm modules doesn't make sense since it has features that only I use, I like to keep it inside codebase not inside the million bundles of node_modules. 

Although executing shell code from lambda revealed that they're placing all the lambda layers stuff to /opt.

`const commonStuff = require("/opt/shared-code")`;

This way it worked. Thanks for your thoughts.

**Comment by nsriram** [comment]
If you have a common code that needs to be used across different lambda functions, and dont want to publish in public npm repository, you have other options _(i would not recommend relying on `/opt` folder reference, as it might change over time & is internal to Lambda architecture today. These containers are ephemeral and its better to rely only till the point of building my layer or lamda)_

1. Package your common code as a separate node module and Use `file:///` reference in your package.json to reference it _(not required to be published)_. If you have more than 1 developer working with you, you have to inform.
2. _(Overhead associated)_ Use a private npm repo and publish your package to it. This depends on how many developers are collaborating with you.
_(Your reference to reusability was not clear in your earlier post.)_
